import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import stylesCounter from "@/styles/Counter.module.css";
import Link from 'next/link';
import { TextInput, Box, Select} from '@mantine/core';
import { useForm } from '@mantine/form';
import { useState } from 'react';


const inter = Inter({ subsets: ['latin'] })

export async function getServerSideProps(){
  const response = await fetch('https://restcountries.com/v3.1/all');
  const results = await response.json();
  return{
    props: {
      data: results
    },
  };
};


export default function Home({ data }) {
  const [selectValue, setSelectValue] = useState('');
  const form = useForm();
  return (
    <>
      <Head>
        <title>Countries</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className='form-section'>
          <div className='container'>
            <Box sx={{ maxWidth: '100%' }} mx="auto">
              <form className='form' onSubmit={form.onSubmit(values => setValue(values))}>
                <TextInput
                  sx={{maxWidth: 480, width: '100%'}}
                  withAsterisk
                  placeholder="Search for a country…"
                  {...form.getInputProps('search')}
                />
           
                <Select
                    onChange={(value) => setSelectValue(value)}
                    placeholder="Filter by Region"
                    data={[
                      { value: 'All', label: 'All' },
                      { value: 'Africa', label: 'Africa' },
                      { value: 'America', label: 'America' },
                      { value: 'Asia', label: 'Asia' },
                      { value: 'Europe', label: 'Europe' },
                      { value: 'Oceania', label: 'Oceania' },
                    ]}
                />
                </form>
            </Box>
          </div>
        </section>

        <section className={stylesCounter.counterSection}>
          <div className='container'>
            <ul className={stylesCounter.list}>
              {
                data.length === 0 ? (<h2>Loading...</h2>) : (
                  data.map(counter => {
                  return <li key={counter.name.common} className={stylesCounter.item}>
                    <Link href={`countries/${counter.name.common}`}>
                    <Image className={stylesCounter.img} layout="intrinsic" src={counter.flags.svg} width='264' height='160' alt="countries's flag"/>
                      <div className={stylesCounter.info}>
                        <h2>{counter.name.common}</h2>
                        <p>Population: {counter.population}</p>
                        <p>Region: {counter.region}</p>
                        <p>Capital: {counter?.capital}</p>
                      </div>
                    </Link>
                  </li>
                })
                )
              }
            </ul>
          </div>
        </section>
      </main>
    </>
  )
};



